server:
  port: 8080
  servlet:
    context-path: /api/metodista
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
#  flyway:
#    locations: classpath:db/migration,classpath:db/data
  datasource:
    name: MetodistaDataSource
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/metodista-kt-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: metodistaPool
      connection-test-query: select now()
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
  jpa:
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
#    properties:
#      jakarta.persistence.schema-generation:
#        create-source: metadata
#        scripts:
#          create-target: create.sql
#          action: create
      hibernate:
        hbm2ddl.delimiter:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non_contextual_creation: true
    show-sql: true
algafood:
  storage:
    local: C:\Users\Felix\Documents\dev\store